<style>@import url(style.css);</style>
[Introduction to Data Analysis](index.html "Course index")

# 1. Setup

As mentioned in the introductory pages, this course uses [R][r], a free and open source software used by data analysts in many different contexts. In the next pages, we explain how to set up R and its companion software [RStudio][rstudio] for the course.

[r]: http://www.r-project.org/ "The R Project"
[rstudio]: http://www.rstudio.com/ "RStudio"

## Computer equipment

Before we start installing and setting up anything, let's review the other tools that you will need to use in this class. You do not need to be a computer nerd to understand what follows. Remember to ask questions in class if things are unclear to you.

- __You will need to bring a fairly recent laptop to class.__ It should be running Mac OS X, Windows or a standard Linux distribution. The software that we use also requires that your computer is equipped with a 64-bit processor, but we also offer support for older 32-bit machines.
- __Make sure that you have decent disk space and memory.__ We recommend something like 4GB of free space on your hard drive, and at least 2GB of live memory (RAM). Check your computer specifications, especially if you are running a 'mini' laptop.
- __Use a modern and secure browser__. Anything but Microsoft Internet Explorer should do. Try [Apple Safari][safari], [Google Chrome][chrome] or [Mozilla Firefox][firefox]. Use bookmarks to keep track of the different pages that will be referred to in class: start by bookmarking the [course index][index].

[index]: index.html
[safari]: https://www.apple.com/safari/ "Apple Safari"
[chrome]: http://www.google.com/chrome "Google Chrome"
[mozilla]: https://www.mozilla.org/en-US/firefox/new/ "Mozilla Firefox"

If your laptop is less than three years old, it probably matches everything in the list above. Tablets and other gadgets won't do. Finally, __do not forget to bring your battery charger__, as well as a USB stick in case the local wifi network fails us.

## Computer skills

Along a laptop with Internet access, you will need to acquire a few computer skills to get through the course without too much hassle. Here's a short selection of such skills, on which we will also work during class.

- __Check that you can install applications.__ This usually requires having admin privileges over your computer, i.e. a username and password combination that gives you the necessary rights to install some software. Also learn to locate the folder where programs are installed on your system.
- __Keep control over files and folders.__ Make sure that you know how to unzip a file and that you know how to browse, locate, move and rename your files efficiently. This is generally easier if you keep things tidy and organized into a single folder accessible from your main screen.
- __Get used to keyboard shortcuts!__ This is the most important bit: to get stuff done efficiently, practice using keyboard shortcuts. This is quicker than pointing and clicking. See, for example, if you know how to select text and browse a page from the keyboard.

These are very generic skills that will serve you in a variety of contexts.

> __Next__: [Installing R](011_r.html).
