<style>@import url(style.css);</style>
<small>[Introduction to Data Analysis](index.html)</small>

# Links

This courses uses the R software, and you will find a lot of links in these pages. That is because the course heavily relies on [examples posted online](http://www.statsblogs.com/) by R enthusiasts, many of whom are professionals from all horizons, from academia to finance to government.

## Tutorials

There's tons of R tutorials out there. [Here's a good one](https://files.nyu.edu/dm141/public/tutdoc/R_intro/html/Introduction%20to%20R.xhtml). [Here's another good one](http://compdiag.molgen.mpg.de/ngfn/docs/2003/jan/R-intro.pdf). In these pages, we do our best to document the R software by example, but you are very welcome to find more relevant resources that better fit your interests.

These tutorials will teach you something new you take the time to read them:

- Winston Chang, [Cookbook for R](http://wiki.stdout.org/rcookbook/) (very good on graphics)
- Robert Kabacoff, [Quick-R](http://www.statmethods.net/) (our favourite reference)
- Chi Yau, [R-Tutor](http://www.r-tutor.com/) (includes basic and more complex techniques)
- [GM-RAM tutorials](http://www.wekaleamstudios.co.uk/supplementary-material/) (includes videos)
- [UCLA statistical guides](http://www.ats.ucla.edu/stat/r/) (more statistically demanding)

You can see from the links above that R is being taught a bit everywhere in the United States and increasingly in Europe. There are a few initiatives in France, including courses at Sciences Po and a [user group](https://fltaur.wordpress.com/) run by [Ensae](http://www.ensae.fr/) and [Insee](http://www.insee.fr/fr/) users.

## Blogs

In addition to R tutorials, there are [R blogs](http://www.r-bloggers.com/) and online communities where R users can share questions and answers about the software. Check out [Cross Validated](http://stats.stackexchange.com/questions/tagged/r) and [Stack Overflow](http://stackoverflow.com/questions/tagged/r), and feel free to sign up (mention the course if you request help on homework).

The visualization component of the course can be explored through [Alberto Cairo's selection of resources](http://www.thefunctionalart.com/2012/10/recommended-readings-for-infographics.html) in that area, which branches with infographics. The most passionate are referred to John P. Boyd's teaching notes on [Scientific Visualization and Information Architecture](http://www-personal.umich.edu/~jpboyd/ENG503.html).

The [SRQM blog](http://srqm.tumblr.com/), created for [another course](http://f.briatte.org/teaching/quanti/), does its best to deliver a regular amount of illustrated links on statistical analysis for the social sciences as well as on data visualization and other related themes.

## Online tools

The following tools require a stable Internet connection:

- [GitHub](https://github.com/) is a code hosting platform that offers [Gist](https://gist.github.com/), a tool used in class to share code snippets.
- [Google Documents](http://docs.google.com/) is a great way to take notes and collaborate over writing reports.
- [RPubs](http://www.rpubs.com/) is an easy way to publish reports [straight from R Studio, using R Markdown](http://blog.rstudio.org/2012/06/04/announcing-rpubs/).

This course uses these tools: it is developed in RStudio with R Markdown, and is available as a [GitHub repository](https://github.com/briatte/ida). The most recent version is available as HTML pages on the [course website](http://f.briatte.org/teaching/ida/). We will also use Google Documents for assignments.

If you find useful online resources for this course, please share them on the [course blog](http://srqm.tumblr.com/), using the "[Suggestions](http://srqm.tumblr.com/submit)" link to let the author know about your find. Your submission will be checked before publication.

> Next: [Setup](10_setup.html).
