<style>@import url(style.css);</style>
<small>[Introduction to Data Analysis](index.html)</small>

# 8. Linear models

This session focuses on (linear) models. The first section covers computation and graphical methods to detect linear trends in your data, using correlation coefficients and scatterplot matrixes. The second section is a rough guide to linear regression, and requires that you read extensively from your handbooks for the mathematical background.

Linear models are commonly used for all sorts of purposes, all of which revolve around different definitions of prediction. Ordinary language defines prediction as forecasting: the ability to estimate something that is not yet in the data. A simple example would be a [prediction of London Olympics 100m men's sprint results][mages]. Let's start by loading the data.

```{r olympics-data}

```

[mages]: http://lamages.blogspot.fr/2012/08/london-olympics-100m-mens-sprint-results.html

> __Next__: [Linear correlation](081_correlation.html).
