<style>@import url(style.css);</style>
<small>[Introduction to Data Analysis](index.html)</small>

# 3.1. Functions

Suppose that you find yourself doing the same computation over and over again. You do not want to type the whole calculations every time you need: you want to program a function that does the job for you.

Take a basic example: the `sum` command adds a vector of numbers together.

```{r sum}
# Create a vector of 99 random [0,1] values.
x <- runif(9)
# Check result: show first 5 values.
head(x)
# Add them up.
sum(x)
```

```{r add-function}
# Define function
add <- function(x,y) {
  x + y
}
# Example.
sum(2,4)
```


## Basic examples

# Examples of recursion

http://www.stat.cmu.edu/~cshalizi/statcomp/

```{r crs-factorial}
# Calculate a factorial
# Input: a number (n)
# Output: the factorial of n
# Presumes: n is a single positive integer
my.factorial <- function(n) {
  if (n == 1) {  # Base case
    return(1)
  } else {  # Recursion
    return(n*my.factorial(n-1))
  }
}
```

> __Next___: [Loops](32_loops.html).
