<style>@import url(style.css);</style>
<small>[Introduction to Data Analysis](index.html)</small>

# 9.2. Smoothing

Looking at [smoothed splines](http://www.johnmarquess.com/?p=111).

Applications to [assault deaths in Europe and the United States](https://github.com/kjhealy/assault-deaths/blob/master/assault-2010.r) and [intentional homicide rates in South America](http://www.quantumforest.com/2012/02/revisiting-homicide-rates/).

Let's start with assault deaths in the United States. The data are from the Bureau of Justice Statistics.

```{r bjs-data}
library(RCurl)
library(ggplot2)
library(reshape)

if(!file.exists("data/bjs2007.csv") | 1==1) {
  # Get raw data.
  bjs <- getURL("https://raw.github.com/briatte/ida/master/data/bjs2007.csv")
  # Turn to text.
  bjs <- textConnection(bjs)
  # Read as CSV.
  bjs <- read.csv(bjs)
  # Save as CSV.
  write.table(bjs, file = "data/bjs2007.csv", row.names = FALSE)
}

# Check 
head(bjs)
tail(bjs)
```

```{r}
bjs <- melt(bjs, id = "Year")
names(bjs) <- c("year", "weapon", "n")
head(bjs)

ggplot(bjs, aes(y = n, x = year)) + geom_line(aes(color = weapon))
```

> __Next week__: [Visualization in space: Maps](100_maps.html).
